[project]
name = ""
version = ""
description = ""
authors = [
    {name = "BalconyJH", email = "balconyjh@gmail.com"},
]
dependencies = [
    "setuptools>=67.8.0",
    "nonebot2[fastapi]>=2.0.0",
    "nonebot-plugin-apscheduler>=0.3.0",
    "nb-cli>=1.1.2",
    "nonebot-adapter-onebot>=2.2.3",
    "nonebot-adapter-kaiheila>=0.2.6",
    "cryptography>=41.0.1",
    "SQLAlchemy>=2.0.16",
    "sqlalchemy-utils>=0.41.1",
    "pymysql>=1.0.3",
]
requires-python = ">=3.11"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
]
plugins = []
plugin_dirs = ["nonebot_plugin_valorant"]
builtin_plugins = ["echo"]
